# Generated by Django 3.0.7 on 2020-06-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200607_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
